FROM postgres
ENV POSTGRES_PASSWORD=8527
ENV POSTGRES_USER=usi
ENV POSTGRES_DB=my_database
COPY \ddl\lib_phys_system.sql /docker-entrypoint-initdb.d/init.sql
# /myDir/init.sql 
# RUN /myDir/init.sql cmd 



